### ISSUE TITLE
Is there an option to allow using just long versions of parameters?

### ISSUE THREAD

**Issue by hughmcl** [j-maly/CommandLineParser#29] opened 2017-03-09 06:51 UTC
I have some code I want to add a parameter to, but I don't want to have a short 1 character version, I just want the long-version.   Is there a way to do that?   If not, I'd like to request as a feature enhancement :)

I could add it as one of the unused characters, but I can see that as getting messy, as some of these options, I don't want to be used on a regular easy going basis :)

           Hugh

**Comment by j-maly** [comment] 2017-03-19 10:16
This is a duplicate of #10

**Closed as completed** 2017-03-19 10:16 UTC

**Comment by j-maly** [comment] 2017-03-19 12:46
Should work in 3.0.6
